---


exp:  exp1
seed: 42

loader:
  image_size:    [12, 256, 256]
  train_batch:   8
  val_batch:     8
  num_workers:   16
  pin_memory:    true
  apply_augment: true

trainer:
  epochs:          100
  accum_iter:      1
  ckpt_freq:       20
  print_freq:      100
  mixed_precision: fp16

optimizer:
  lr:           0.001
  betas:        [0.9, 0.999]
  amsgrad:      true
  weight_decay: 0.01

scheduler:
  min_lr: 0.0
  warmup: 10

model:
  name: vt2unet
  params:
    image_size:       [12, 256, 256]
    patch_size:       [2, 4, 4]
    window_size:      [2, 8, 8]
    input_dims:       15
    output_dims:      1
    embed_dims:       48
    depths:           [2, 2, 2, 2]
    num_heads:        [3, 6, 12, 24]
    mlp_ratio:        4.0
    qkv_bias:         true
    drop_rate:        0.0
    attn_drop_rate:   0.0
    drop_path_rate:   0.1
    patch_norm:       true
    skip_connect:     true
    apply_cross_attn: true


...