---


exp:  swin_unetr/exp2
seed: 42
cv:   4

loader:
  image_size:    [12, 256, 256]
  train_batch:   8
  val_batch:     8
  num_workers:   16
  pin_memory:    true
  apply_augment: true

trainer:
  epochs:     50
  accum_iter: 1
  ckpt_freq:  50
  print_freq: 200

loss:
  rec:
    mode: mse

optimizer:
  lr:           0.001
  betas:        [0.9, 0.999]
  amsgrad:      true
  weight_decay: 0.01

scheduler:
  min_lr: 0.0
  warmup: 5

model:
  name: swin_unetr
  params:
    image_size:     [12, 256, 256]
    patch_size:     [1, 2, 2]
    window_size:    [3, 7, 7]
    in_channels:    15
    out_channels:   1
    depths:         [2, 2, 2, 2]
    num_heads:      [3, 6, 12, 24]
    feature_size:   24
    norm_name:      batch
    drop_rate:      0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.1


...